#ifndef _TANK_VERTICES_BIN_H
#define _TANK_VERTICES_BIN_H
/* Auto-generated by bin2c.py */
#include <stddef.h>
#include "fixedpt.h"

extern const fixedpt tank_vertices_bin_start[];
extern const size_t tank_vertices_bin_size;

#endif
