#ifndef _TANK_FACES_BIN_H
#define _TANK_FACES_BIN_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char tank_faces_bin_start[];
extern const size_t tank_faces_bin_size;

#endif
